### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/confique#1]
There are still several things I absolutely want to add. This issue is mostly just a note to myself.

**Soon**

- [x] `format` should mention env variables
- [ ] Add `from` attribute to deserialize into another type and then use `From` or `TryFrom`
    - Or sth like `parse`
- [ ] Validation
- [ ] Rename?
- [ ] Forward other derives??? (or maybe not, just derive `Debug` for Partial)
    - We cannot see other derives, only in special circumstances
    - Thus we probably want `#[config(derive_for_partial = Debug)]` or sth
    - Maybe a more general attribute forward?

**Later**
- [ ] More `format` options. Maybe we don't need one `Option` type per file format?
- [x] Tests
- [ ] Make sure error messages when misusing proc macro are good. Also when fields don't implement `Deserialize` and stuff.
- [x] Arrays as default values
- [ ] Deserialize sequences from env via comma separated values?
- [ ] `config.{toml,yaml}` kind of syntax? Mhhh probably not?
- [x] Think about env deserialization again
- [ ] Nested `Vec<_>` and `HashMap<_, _>` maybe?

**Comment by amkartashov** [comment]
What about allowing to derive Config for enums? I started using your library in my project and have `oneof` fields described by enums. I parse it with serde fow now, so it's a mixed approach.

**Comment by bwidawsk** [comment]
I'd really like support for default array values.

**Comment by LukasKalbertodt** [comment]
> I'd really like support for default array values.

I implemented this now. Still haven't pushed/released, but that should happen in the coming days.

**Comment by LukasKalbertodt** [comment]
Locking this issue as it was meant as a note to myself. For comments or other feature requests, feel free to just open a new issue!

**Comment by LukasKalbertodt** [comment]
Array default values are release with 0.2.0.

I will close this as all still relevant points have their own issue now.
