### ISSUE TITLE
`invalid type: string` when trying to deserialize an enum

### ISSUE THREAD

**Issue by NyCodeGHG** [LukasKalbertodt/confique#31]
Hi, I'm trying to deserialize an enum of options, but it fails with the following error.
`invalid type: string "B", expected enum Strategy'

Minimal Example: https://codesandbox.io/p/sandbox/nostalgic-meadow-jstg4k?file=%2Fsrc%2Fmain.rs%3A7%2C2

**Comment by LukasKalbertodt** [comment]
Thanks for the report! Fix is released as 0.2.4
