### ISSUE TITLE
Warning about missing docs (in private items)

### ISSUE THREAD

**Issue by scullionw** [LukasKalbertodt/confique#33]
same as https://github.com/LukasKalbertodt/confique/issues/25

but for `#![deny(clippy::missing_docs_in_private_items)]`

To reproduce:
1. Have a config struct that the lib does not make public
2. Use #![deny(clippy::missing_docs_in_private_items)]

<img width="1556" alt="Screenshot 2023-08-29 at 10 00 12 AM" src="https://github.com/LukasKalbertodt/confique/assets/11668344/b3cfc63b-2457-483d-9081-2d01e959167b">

Seems like the doc comment is not passed through in this case?

**Comment by LukasKalbertodt** [comment]
And I assume you can't simply annotate your struct with `#[allow(clippy::missing_docs_in_private_items)]`? 

So this crate would have to add said attribute to some items. Now I wonder:
- Is it ok to just add the attribute even if I don't use clippy at all? 
- Clippy could always add new lints that I don't know about. No point in adding hundreds of individual attributes to silence every lint individually. Shouldn't clippy just ignore generated code? Or should this crate just add `#[allow(warnings)]` to generated code? :thinking:

**Comment by LukasKalbertodt** [comment]
I cannot reproduce this. Regardless of whether I make the struct `pub` or not, as long as the struct itself has docs, no warnings are emitted from the code generated by confique.
