### ISSUE TITLE
env yes|no booleans?

### ISSUE THREAD

**Issue by jdx** [LukasKalbertodt/confique#34]
https://github.com/LukasKalbertodt/confique/blob/0a79a43a72bfcb6757d7930cdda18d1ed8019413/src/env/mod.rs#L90

what are your thoughts about accepting FOO=yes|no as valid entries for true/false? I switched to confique for my app but it broke some users since I was using those before

**Comment by LukasKalbertodt** [comment]
That sounds quite reasonable! I am aware of the YAML Norwegian problem, but I don't think this is a problem here. Should be unambiguous. 

But while we're at it: what's your opinion on only allowing a fully lowercase and fully uppercase version? Should it rather just make a case-insensitive comparison? Especially with "yes", I could imagine "Yes" to be a common spelling.

**Comment by LukasKalbertodt** [comment]
Release as v0.2.5
